In [1]:
import pandas as pd
import os
import csv
from sqlalchemy import create_engine

In [2]:
#Labor of Statistics Data Manipulation

In [3]:
csv_file = "mwe-2020complete.csv"
labor_statistics = pd.read_csv(csv_file, low_memory = False)
labor_statistics

,Series title,Area level,Area text,City,State,State Name,Occupation text,Job characteristic text,Work level text,Average hourly wage\n($),Relative standard \nerror,Average \nhourly wage footnote,Relative standard error footnote,Series ID,Area code,Occupation \ncode,Job characteristic code,Work level code
0,Average hourly wage for level 07 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Financial managers,All workers,Level 07,23.45,8.1,NaN,NaN,WMU00101801020000001100000007,10180,110000,0,7
1,Average hourly wage for level 09 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 09,29.09,2.9,NaN,NaN,WMU00101801020000001100000009,10180,110000,0,9
2,Average hourly wage for level 10 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 10,32.68,12.9,NaN,NaN,WMU00101801020000001100000010,10180,110000,0,10
3,Average hourly wage for level 11 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 11,46.37,3.9,NaN,NaN,WMU00101801020000001100000011,10180,110000,0,11
4,Average hourly wage for level 12 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 12,48.15,11.5,NaN,NaN,WMU00101801020000001100000012,10180,110000,0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433764,Average hourly wage for full-time level 02 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Full-time,Level 02,16.18,4.7,NaN,NaN,WMU56000071020000005370652502,5600007,537065,25,2
433765,Average hourly wage for full-time level 03 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Full-time,Level 03,18.56,12.2,NaN,NaN,WMU56000071020000005370652503,5600007,537065,25,3
433766,Average hourly wage for part-time stockers and...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Part-time,All levels,12.29,3.4,NaN,NaN,WMU56000071020000005370652600,5600007,537065,26,0
433767,Average hourly wage for part-time level 02 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Part-time,Level 02,13.84,4.7,NaN,NaN,WMU56000071020000005370652602,5600007,537065,26,2
433768,Average hourly wage for time-based stockers an...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Time-based pay,All levels,15.05,4.9,NaN,NaN,WMU56000071020000005370652700,5600007,537065,27,0

In [4]:
type(labor_statistics)

pandas.core.frame.DataFrame

In [5]:
labor_statistics.dtypes

Series title                         object
Area level                           object
Area text                            object
City                                 object
State                                object
State Name                           object
Occupation text                      object
Job characteristic text              object
Work level text                      object
Average hourly wage\n($)             object
Relative standard \nerror            object
Average \nhourly wage footnote      float64
Relative standard error footnote    float64
Series ID                            object
Area code                             int64
Occupation \ncode                     int64
Job characteristic code               int64
Work level code                       int64
dtype: object

In [6]:
hourly_wage_renamecolumn = labor_statistics.rename(columns={"Average hourly wage\n($)": "Hourly Wage", "State": "State Abbreviation", "State Name": "State"})
hourly_wage_renamecolumn

,Series title,Area level,Area text,City,State Abbreviation,State,Occupation text,Job characteristic text,Work level text,Hourly Wage,Relative standard \nerror,Average \nhourly wage footnote,Relative standard error footnote,Series ID,Area code,Occupation \ncode,Job characteristic code,Work level code
0,Average hourly wage for level 07 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Financial managers,All workers,Level 07,23.45,8.1,NaN,NaN,WMU00101801020000001100000007,10180,110000,0,7
1,Average hourly wage for level 09 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 09,29.09,2.9,NaN,NaN,WMU00101801020000001100000009,10180,110000,0,9
2,Average hourly wage for level 10 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 10,32.68,12.9,NaN,NaN,WMU00101801020000001100000010,10180,110000,0,10
3,Average hourly wage for level 11 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 11,46.37,3.9,NaN,NaN,WMU00101801020000001100000011,10180,110000,0,11
4,Average hourly wage for level 12 management oc...,Metro area,"Abilene, TX",Abilene,TX,Texas,Management occupations,All workers,Level 12,48.15,11.5,NaN,NaN,WMU00101801020000001100000012,10180,110000,0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433764,Average hourly wage for full-time level 02 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Full-time,Level 02,16.18,4.7,NaN,NaN,WMU56000071020000005370652502,5600007,537065,25,2
433765,Average hourly wage for full-time level 03 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Full-time,Level 03,18.56,12.2,NaN,NaN,WMU56000071020000005370652503,5600007,537065,25,3
433766,Average hourly wage for part-time stockers and...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Part-time,All levels,12.29,3.4,NaN,NaN,WMU56000071020000005370652600,5600007,537065,26,0
433767,Average hourly wage for part-time level 02 sto...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Part-time,Level 02,13.84,4.7,NaN,NaN,WMU56000071020000005370652602,5600007,537065,26,2
433768,Average hourly wage for time-based stockers an...,Nonmetro area,Eastern Wyoming nonmetropolitan area,Eastern Wyoming nonmetropolitan area,NaN,Wyoming,Stockers and order fillers,Time-based pay,All levels,15.05,4.9,NaN,NaN,WMU56000071020000005370652700,5600007,537065,27,0

In [7]:
#labor_statistics.rename(columns={labor_statistics.columns[9]: "Hourly"})

In [8]:
hourly_wage_by_state = hourly_wage_renamecolumn[["Hourly Wage","State"]]
hourly_wage_by_state

       Hourly Wage    State
0            23.45    Texas
1            29.09    Texas
2            32.68    Texas
3            46.37    Texas
4            48.15    Texas
...            ...      ...
433764       16.18  Wyoming
433765       18.56  Wyoming
433766       12.29  Wyoming
433767       13.84  Wyoming
433768       15.05  Wyoming

[433769 rows x 2 columns]

In [9]:

#Vi's Part - U.S. Vaccinations

In [10]:
#import os
#import pandas as pd
#import csv

In [11]:
csv_path = "US_covid19_vaccinations.csv"

In [12]:
data = pd.read_csv(csv_path)
data.head()

,State,Total Doses Delivered,Doses Delivered per 100K,18+ Doses Delivered per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent of 12+ Pop with at least One Dose by State of Residence,People 12+ Fully Vaccinated by State of Residence,Percent of 12+ Pop Fully Vaccinated by State of Residence,People 12+ Fully Vaccinated_Moderna_Resident,People 12+ Fully Vaccinated_Pfizer_Resident,People 12+ Fully Vaccinated_Janssen_Resident,People 12+ Fully Vaccinated_Unknown 2-dose Manuf_Resident,12+ Doses Administered by State where Administered,Doses Administered per 100k of 12+ pop by State where Administered,Doses Delivered per 100k of 12+ pop
0,Alaska,980975,134096.0,177854.0,747155,102134.0,694622,125937.0,403340,55.1,...,66.0,350342,57.5,137527,182923,29837,55,745009,122358,161112
1,Alabama,6294340,128372.0,164994.0,4237710,86428.0,4035003,105770.0,2485579,50.7,...,59.4,1930034,46.1,827938,964629,137132,335,4237314,101205,150335
2,Arkansas,3785520,125440.0,163334.0,2866219,94977.0,2677921,115545.0,1630602,54.0,...,63.6,1292077,50.5,556758,641711,93031,577,2861023,111879,148031
3,American Samoa,58530,105102.0,134939.0,56971,102302.0,48908,112756.0,31481,56.5,...,66.2,26081,54.8,6331,19197,553,0,56957,119766,123073
4,Arizona,9504840,130584.0,168571.0,7911114,108688.0,7391979,131099.0,4191297,57.6,...,67.5,3585589,57.8,1409110,1902513,270414,3552,7910090,127458,153154

In [13]:
#rename new york sate
data['State'] = data['State'].replace(['New York State'],'New York')

In [14]:
#Create US States list
states_list = 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'

In [15]:
# keep the state in our us States list
data = data[data['State'].isin(states_list)]         
data = data.reset_index(drop = True)
data.head(10)

,State,Total Doses Delivered,Doses Delivered per 100K,18+ Doses Delivered per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent of 12+ Pop with at least One Dose by State of Residence,People 12+ Fully Vaccinated by State of Residence,Percent of 12+ Pop Fully Vaccinated by State of Residence,People 12+ Fully Vaccinated_Moderna_Resident,People 12+ Fully Vaccinated_Pfizer_Resident,People 12+ Fully Vaccinated_Janssen_Resident,People 12+ Fully Vaccinated_Unknown 2-dose Manuf_Resident,12+ Doses Administered by State where Administered,Doses Administered per 100k of 12+ pop by State where Administered,Doses Delivered per 100k of 12+ pop
0,Alaska,980975,134096.0,177854.0,747155,102134.0,694622,125937.0,403340,55.1,...,66.0,350342,57.5,137527,182923,29837,55,745009,122358,161112
1,Alabama,6294340,128372.0,164994.0,4237710,86428.0,4035003,105770.0,2485579,50.7,...,59.4,1930034,46.1,827938,964629,137132,335,4237314,101205,150335
2,Arkansas,3785520,125440.0,163334.0,2866219,94977.0,2677921,115545.0,1630602,54.0,...,63.6,1292077,50.5,556758,641711,93031,577,2861023,111879,148031
3,Arizona,9504840,130584.0,168571.0,7911114,108688.0,7391979,131099.0,4191297,57.6,...,67.5,3585589,57.8,1409110,1902513,270414,3552,7910090,127458,153154
4,California,56160135,142134.0,183424.0,48668051,123172.0,45018684,147035.0,27515288,69.6,...,81.5,22323922,66.3,8294031,12244540,1781544,3807,48539122,144263,166913
5,Colorado,7930975,137721.0,176275.0,6905875,119920.0,6409646,142461.0,3682433,63.9,...,74.4,3304643,66.9,1280028,1769692,253547,1376,6885823,139500,160674
6,Connecticut,5385255,151047.0,189766.0,4871494,136637.0,4510226,158931.0,2647293,74.3,...,85.2,2375379,76.5,857662,1318457,198952,308,4869789,156789,173385
7,Delaware,1482145,152208.0,192438.0,1164472,119585.0,1090115,141538.0,629240,64.6,...,74.9,544432,64.8,201616,293561,48845,410,1164274,138636,176486
8,Florida,30861835,143692.0,178932.0,25243875,117535.0,23925808,138718.0,13843588,64.5,...,74.0,11546918,61.8,4146415,6217972,1157590,24941,25235140,134976,165072
9,Georgia,13636825,128438.0,168075.0,9949267,93707.0,9373917,115534.0,5518435,52.0,...,61.4,4469165,49.7,1777855,2428707,260516,2087,9946861,110667,151721

In [16]:
# drop some columns over 12 years old 
data.drop(columns=["Doses Delivered per 100k of 12+ pop", "Doses Administered per 100k of 12+ pop by State where Administered", "12+ Doses Administered by State where Administered","People 12+ Fully Vaccinated_Unknown 2-dose Manuf_Resident", "People 12+ Fully Vaccinated_Janssen_Resident", "People 12+ Fully Vaccinated_Pfizer_Resident", "People 12+ Fully Vaccinated_Moderna_Resident", "Percent of 12+ Pop Fully Vaccinated by State of Residence", "People 12+ Fully Vaccinated by State of Residence", "Percent of 12+ Pop with at least One Dose by State of Residence", "People 12+ with at least One Dose by State of Residence"], inplace = True)
data

,State,Total Doses Delivered,Doses Delivered per 100K,18+ Doses Delivered per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent of 65+ Pop with at least One Dose by State of Residence,People 65+ Fully Vaccinated by State of Residence,Percent of 65+ Pop Fully Vaccinated by State of Residence,People 65+ Fully Vaccinated_Moderna_Resident,People 65+ Fully Vaccinated_Pfizer_Resident,People 65+ Fully Vaccinated_Janssen_Resident,People 65+ Fully Vaccinated_Unknown 2-dose Manuf_Resident,65+ Doses Administered by State where Administered,Doses Administered per 100k of 65+ pop by State where Administered,Doses Delivered per 100k of 65+ pop
0,Alaska,980975,134096.0,177854.0,747155,102134.0,694622,125937.0,403340,55.1,...,85.0,72845,79.5,40666,29196,2958,25,149119,162815,1071070
1,Alabama,6294340,128372.0,164994.0,4237710,86428.0,4035003,105770.0,2485579,50.7,...,85.2,621517,73.1,328624,258569,34114,210,1309370,154073,740653
2,Arkansas,3785520,125440.0,163334.0,2866219,94977.0,2677921,115545.0,1630602,54.0,...,84.3,373075,71.2,212262,146581,13902,330,813123,155211,722590
3,Arizona,9504840,130584.0,168571.0,7911114,108688.0,7391979,131099.0,4191297,57.6,...,88.0,1004471,76.8,493816,463843,44927,1885,2293636,175270,726318
4,California,56160135,142134.0,183424.0,48668051,123172.0,45018684,147035.0,27515288,69.6,...,98.2,4626397,79.2,2347054,2098748,179364,1231,10401145,178159,961957
5,Colorado,7930975,137721.0,176275.0,6905875,119920.0,6409646,142461.0,3682433,63.9,...,90.3,693301,82.3,339499,330176,23144,482,1487331,176556,941460
6,Connecticut,5385255,151047.0,189766.0,4871494,136637.0,4510226,158931.0,2647293,74.3,...,98.1,576617,91.5,227605,328968,19979,65,1200932,190550,854471
7,Delaware,1482145,152208.0,192438.0,1164472,119585.0,1090115,141538.0,629240,64.6,...,96.5,163172,86.4,67175,86638,9136,223,349022,184760,784594
8,Florida,30861835,143692.0,178932.0,25243875,117535.0,23925808,138718.0,13843588,64.5,...,94.9,3715458,82.6,1811409,1693819,194630,15600,8426879,187375,686225
9,Georgia,13636825,128438.0,168075.0,9949267,93707.0,9373917,115534.0,5518435,52.0,...,85.6,1127635,74.3,621264,474191,31221,959,2529344,166738,898961
10,Hawaii,2161810,152684.0,193710.0,1806078,127559.0,1693829,151776.0,1059853,74.9,...,99.9,230044,85.7,95753,123527,9352,1412,498949,185864,805299
11,Iowa,3972115,125896.0,163581.0,3329385,105525.0,3131146,128948.0,1786364,56.6,...,90.8,484749,87.7,255572,216035,13039,103,986479,178402,718345
12,Idaho,2059860,115265.0,153851.0,1483990,83041.0,1483040,110769.0,802887,44.9,...,84.5,230488,79.3,106365,113260,10664,199,478618,164660,708659
13,Illinois,17119345,135098.0,173731.0,14825616,116997.0,13737381,139410.0,8454047,66.7,...,94.0,1578116,77.2,716797,785252,73343,2724,3523215,172433,837856
14,Indiana,7843830,116512.0,151887.0,6486086,96344.0,6115021,118411.0,3410605,50.7,...,85.6,900822,83.0,444040,425294,27982,3506,1878314,172998,722439
15,Kansas,3634085,124741.0,164211.0,2952093,101331.0,2762497,124827.0,1688828,58.0,...,96.3,395647,83.2,190022,188776,16677,172,829554,174464,764287
16,Kentucky,5357945,119927.0,154639.0,4652972,104148.0,4388285,126653.0,2597915,58.1,...,90.8,615423,82.0,280734,296816,37314,559,1263744,168373,713856
17,Louisiana,5417300,116531.0,152122.0,4285260,92180.0,4070319,114297.0,2331670,50.2,...,85.9,598930,80.8,284536,293385,20870,139,1258054,169773,731058
18,Massachusetts,10579270,153490.0,190972.0,9555924,138642.0,8872636,160164.0,5231716,75.9,...,98.8,1030759,88.1,467708,495039,67978,34,2137462,182793,904728
19,Maryland,9512770,157348.0,201927.0,7688158,127168.0,7112741,150982.0,4160501,68.8,...,95.0,859016,89.5,407691,398488,52067,770,1737098,181062,991537
20,Maine,2052590,152698.0,187388.0,1755434,130592.0,1651471,150768.0,968273,72.0,...,97.5,263969,92.5,120573,120799,22514,83,524680,183927,719538
21,Michigan,13032880,130500.0,166174.0,10276607,102901.0,9694666,123610.0,5554589,55.6,...,87.4,1464182,82.9,731145,666761,65771,505,2947367,166952,738239
22,Minnesota,7444750,132008.0,171677.0,6456499,114484.0,5987407,138071.0,3514636,62.3,...,94.1,815636,88.6,343510,424353,47644,129,1645765,178813,808876
23,Missouri,7484365,121946.0,157009.0,6030432,98257.0,5684334,119247.0,3267893,53.2,...,85.1,820466,77.3,374934,408749,36713,70,1741698,163996,704718
24,Mississippi,3593575,120746.0,157781.0,2572591,86440.0,2435134,106918.0,1420096,47.7,...,82.8,369130,75.8,189616,163047,16363,104,774462,159127,738366
25,Montana,1268795,118715.0,151013.0,1031579,96519.0,978431,116454.0,562731,52.7,...,85.5,164015,79.5,78964,76077,8838,136,336068,162794,614616
26,North Carolina,13561110,129300.0,165635.0,10674292,101775.0,10013614,122306.0,5949430,56.7,...,88.0,1379428,78.8,663118,671477,44794,39,2943083,168071,774436
27,North Dakota,865350,113554.0,148713.0,708323,92948.0,672293,115536.0,373170,49.0,...,85.6,91065,76.0,44866,42472,3727,0,199343,166334,722058
28,Nebraska,2402500,124198.0,164743.0,2093877,108244.0,1950806,133769.0,1122920,58.0,...,90.8,272245,87.1,132897,132280,6308,760,568020,181791,768903
29,New Hampshire,2048340,150645.0,185461.0,1703657,125296.0,1593289,144260.0,921755,67.8,...,96.8,222864,87.8,93935,114826,14082,21,448104,176513,806865
30,New Jersey,13235605,149013.0,190616.0,11147167,125500.0,10361203,149219.0,6277465,70.7,...,93.5,1260679,85.4,589675,587027,83939,38,2538415,172034,897004
31,New Mexico,2765525,131891.0,170607.0,2679516,127789.0,2481976,153115.0,1482909,70.7,...,97.7,333549,88.3,154561,158723,19446,819,689053,182479,732384
32,Nevada,3784610,122871.0,158517.0,3255635,105697.0,3057906,128079.0,1809303,58.7,...,86.3,379402,76.5,178319,177662,23403,18,808994,163113,763069
33,New York,27865255,143240.0,180647.0,24742907,127190.0,23244030,150688.0,13299568,68.4,...,89.9,2730349,82.8,1299754,1260957,168728,910,5664732,171859,845389
34,Ohio,14190665,121401.0,155752.0,11749364,100516.0,11109178,121930.0,6189482,53.0,...,86.3,1690329,82.6,768392,834913,84573,2451,3480819,170101,693472
35,Oklahoma,4776510,120711.0,158966.0,3906825,98733.0,3679325,122451.0,2144418,54.2,...,89.5,498698,78.5,255375,224639,18660,24,1076639,169514,752050
36,Oregon,6334105,150178.0,189011.0,5039395,119481.0,4710666,140568.0,2732729,64.8,...,89.9,651666,85.1,295365,307401,48549,351,1302526,170025,826820
37,Pennsylvania,18177655,141991.0,178784.0,15606032,121903.0,14699648,144577.0,8981050,70.2,...,99.9,2067893,86.4,975930,1007656,84098,209,4599916,192195,759503
38,Rhode Island,1648185,155583.0,192800.0,1410438,133140.0,1318886,154280.0,768150,72.5,...,98.6,174565,93.3,79461,88925,6133,46,357551,191157,881166
39,South Carolina,6434505,124973.0,159367.0,4930206,95756.0,4676223,115819.0,2712248,52.7,...,88.9,741424,79.1,316019,397380,27857,168,1579750,168592,686697
40,South Dakota,1104205,124817.0,165410.0,913607,103272.0,858911,128665.0,503489,56.9,...,94.1,133207,87.7,68320,60631,4244,12,269195,177252,727068
41,Tennessee,8061440,118044.0,151556.0,6417238,93968.0,6115713,114976.0,3430805,50.2,...,84.0,870339,76.1,434467,399943,32098,3831,1915885,167561,705045
42,Texas,39269685,135432.0,181837.0,30744502,106031.0,28348839,131269.0,16786802,57.9,...,87.7,2918538,78.2,1088770,1585788,243821,159,6366575,170492,1051610
43,Utah,3860040,120402.0,169689.0,3277366,102227.0,2987187,131318.0,1825788,56.9,...,93.5,300162,82.0,130370,154459,15332,1,640703,175117,1055030
44,Virginia,11986815,140435.0,179587.0,10383388,121649.0,9602056,143858.0,5636965,66.0,...,92.5,1144103,84.2,541356,535892,66380,475,2382027,175290,882093
45,Vermont,1000270,160303.0,196138.0,880078,141041.0,821935,161169.0,477539,76.5,...,99.9,118370,94.7,57565,58426,2232,147,253691,202889,799966
46,Washington,10745165,141107.0,180535.0,9592586,125971.0,8953007,150424.0,5218907,68.5,...,94.8,1072889,88.7,487904,525999,57798,1188,2210684,182743,888234
47,Wisconsin,7065045,121342.0,155077.0,6556008,112599.0,6166244,135348.0,3458026,59.4,...,92.9,912188,89.7,441349,443283,27400,156,1901776,186954,694529
48,West Virginia,2856645,159398.0,199406.0,1520726,84855.0,1449761,101199.0,847818,47.3,...,78.9,260217,70.9,132660,120822,6628,107,544455,148348,778354
49,Wyoming,602635,104125.0,135416.0,491080,84851.0,468085,105182.0,266342,46.0,...,81.8,74856,75.5,38396,33098,3337,25,154194,155470,607624

In [17]:
# create a new table for use
data_df = data[["State","Total Doses Delivered", "Doses Delivered per 100K", "People with at least One Dose by State of Residence", "Percent of Total Pop with at least One Dose by State of Residence", "People Fully Vaccinated by State of Residence", "Percent of Total Pop Fully Vaccinated by State of Residence", "Total Number of Janssen doses administered", "Total Number of Moderna doses administered", "Total Number of Pfizer doses adminstered", "Total Number of doses from unknown manufacturer administered", "People Fully Vaccinated Moderna Resident", "People Fully Vaccinated Pfizer Resident", "People Fully Vaccinated Janssen Resident", "People Fully Vaccinated Unknown 2-dose manufacturer Resident", "People with 2 Doses by State of Residence", "Percent of Total Pop with 2 Doses by State of Residence"]]
data_df

,State,Total Doses Delivered,Doses Delivered per 100K,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,People Fully Vaccinated by State of Residence,Percent of Total Pop Fully Vaccinated by State of Residence,Total Number of Janssen doses administered,Total Number of Moderna doses administered,Total Number of Pfizer doses adminstered,Total Number of doses from unknown manufacturer administered,People Fully Vaccinated Moderna Resident,People Fully Vaccinated Pfizer Resident,People Fully Vaccinated Janssen Resident,People Fully Vaccinated Unknown 2-dose manufacturer Resident,People with 2 Doses by State of Residence,Percent of Total Pop with 2 Doses by State of Residence
0,Alaska,980975,134096.0,403340,55.1,351155,48.0,32068,302636,412230,221,137531,183730,29839,55,321505,43.9
1,Alabama,6294340,128372.0,2485579,50.7,1930090,39.4,134719,1888927,2214058,6,827950,964664,137141,335,1793775,36.6
2,Arkansas,3785520,125440.0,1630602,54.0,1293559,42.9,94957,1258183,1510860,2219,556765,643068,93148,578,1200921,39.8
3,Arizona,9504840,130584.0,4191297,57.6,3585953,49.3,279677,3253869,4366160,11408,1409134,1902618,270648,3553,3316949,45.6
4,California,56160135,142134.0,27515288,69.6,22372573,56.6,1793339,18878544,27983640,12528,8294455,12292423,1781880,3815,20604202,52.1
5,Colorado,7930975,137721.0,3682433,63.9,3312718,57.5,257832,2762708,3880797,4538,1280043,1777728,253570,1377,3060939,53.2
6,Connecticut,5385255,151047.0,2647293,74.3,2375843,66.6,199768,1826907,2843930,889,857867,1318637,199030,309,2177478,61.1
7,Delaware,1482145,152208.0,629240,64.6,544474,55.9,49486,453411,660524,1051,201620,293590,48854,410,495834,50.9
8,Florida,30861835,143692.0,13843588,64.5,11548538,53.8,1175153,9624012,14362812,81898,4147064,6218172,1158360,24942,10396364,48.4
9,Georgia,13636825,128438.0,5518435,52.0,4469605,42.1,262210,4069257,5611647,6153,1777901,2428998,260616,2090,4211632,39.7
10,Hawaii,2161810,152684.0,1059853,74.9,790588,55.8,45039,609491,1057779,93769,265308,461493,45700,18087,744975,52.6
11,Iowa,3972115,125896.0,1786364,56.6,1644060,52.1,141840,1352780,1834436,329,649796,854449,139586,229,1504900,47.7
12,Idaho,2059860,115265.0,802887,44.9,709729,39.7,62521,617980,801697,1792,281002,366078,62174,475,647893,36.3
13,Illinois,17119345,135098.0,8454047,66.7,6564555,51.8,536218,5477990,8793604,17804,2341442,3692801,524570,5742,6042084,47.7
14,Indiana,7843830,116512.0,3410605,50.7,3144755,46.7,245616,2445297,3771819,23354,1145522,1750628,241556,7049,2905012,43.2
15,Kansas,3634085,124741.0,1688828,58.0,1424067,48.9,102928,1194711,1653500,954,554198,767970,101544,355,1323003,45.4
16,Kentucky,5357945,119927.0,2597915,58.1,2207753,49.4,192797,1969238,2490219,718,890398,1126266,190060,1029,2018405,45.2
17,Louisiana,5417300,116531.0,2331670,50.2,1978133,42.6,153432,1826499,2303989,1340,813587,1017763,146168,615,1832598,39.4
18,Massachusetts,10579270,153490.0,5231716,75.9,4582154,66.5,325417,3732188,5498100,219,1712485,2542466,327097,106,4256457,61.8
19,Maryland,9512770,157348.0,4160501,68.8,3756767,62.1,290702,2882483,4504922,10051,1352508,2116623,284839,2797,3475055,57.5
20,Maine,2052590,152698.0,968273,72.0,890002,66.2,113828,722378,918423,805,342528,434944,112329,201,778050,57.9
21,Michigan,13032880,130500.0,5554589,55.6,5083552,50.9,360014,4082223,5832827,1543,1952042,2764363,366306,841,4718475,47.2
22,Minnesota,7444750,132008.0,3514636,62.3,3190059,56.6,288381,2439215,3727134,1769,1145463,1754824,289178,594,2902001,51.5
23,Missouri,7484365,121946.0,3267893,53.2,2809394,45.8,200011,2215918,3613748,755,1006766,1600712,201721,195,2608752,42.5
24,Mississippi,3593575,120746.0,1420096,47.7,1178170,39.6,70818,1076416,1424034,1323,479281,628471,70179,239,1108444,37.2
25,Montana,1268795,118715.0,562731,52.7,495465,46.4,44305,449738,536769,767,207690,244279,43255,241,452528,42.3
26,North Carolina,13561110,129300.0,5949430,56.7,4943928,47.1,394688,4079432,6199707,465,1810071,2745725,388050,82,4556340,43.4
27,North Dakota,865350,113554.0,373170,49.0,321719,42.2,31214,289796,387312,1,128650,164770,28298,1,293462,38.5
28,Nebraska,2402500,124198.0,1122920,58.0,1021127,52.8,76779,795116,1217686,4296,374777,568239,76923,1188,944672,48.8
29,New Hampshire,2048340,150645.0,921755,67.8,819004,60.2,78073,680905,944652,27,319813,432298,66850,43,752316,55.3
30,New Jersey,13235605,149013.0,6277465,70.7,5524013,62.2,426117,4360385,6360635,30,2052029,3039612,432237,135,5092988,57.3
31,New Mexico,2765525,131891.0,1482909,70.7,1274164,60.8,96034,1142068,1436221,5193,512891,665072,94670,1531,1180052,56.3
32,Nevada,3784610,122871.0,1809303,58.7,1497539,48.6,146507,1186756,1922350,22,536262,817148,144098,31,1353664,43.9
33,New York,27865255,143240.0,13299568,68.4,11868703,61.0,1080609,9434676,14219408,8214,4364385,6475051,1027170,2097,10844585,55.7
34,Ohio,14190665,121401.0,6189482,53.0,5710919,48.9,487797,4646110,6598509,16948,2162349,3072055,471636,4879,5241848,44.8
35,Oklahoma,4776510,120711.0,2144418,54.2,1768580,44.7,116021,1655701,2134900,203,723245,930722,114527,86,1654503,41.8
36,Oregon,6334105,150178.0,2732729,64.8,2475493,58.7,207520,1926794,2901586,3495,904928,1365324,204463,778,2272087,53.9
37,Pennsylvania,18177655,141991.0,8981050,70.2,7146396,55.8,626149,6284163,8695022,698,2736272,3781205,628483,436,6519165,50.9
38,Rhode Island,1648185,155583.0,768150,72.5,694145,65.5,51106,542076,816642,614,256112,386561,51333,139,643065,60.7
39,South Carolina,6434505,124973.0,2712248,52.7,2280215,44.3,174051,1950261,2804796,1098,851554,1257352,171045,264,2109837,41.0
40,South Dakota,1104205,124817.0,503489,56.9,439521,49.7,30997,379299,503235,76,179380,229090,31032,19,408554,46.2
41,Tennessee,8061440,118044.0,3430805,50.2,2894479,42.4,200161,2504249,3687056,25772,1088188,1605917,193451,6923,2702660,39.6
42,Texas,39269685,135432.0,16786802,57.9,14031430,48.4,1205886,11885833,17651946,837,5234470,7623980,1172215,765,12865983,44.4
43,Utah,3860040,120402.0,1825788,56.9,1545911,48.2,143910,1256914,1876542,0,567523,837001,141383,4,1405256,43.8
44,Virginia,11986815,140435.0,5636965,66.0,4947779,58.0,380620,3816963,6182342,3463,1759347,2813703,373463,1266,4576354,53.6
45,Vermont,1000270,160303.0,477539,76.5,426323,68.3,42529,354765,482052,732,161642,223216,41217,248,385276,61.7
46,Washington,10745165,141107.0,5218907,68.5,4618179,60.6,406750,3700853,5478484,6499,1722153,2489042,404858,2126,4215580,55.4
47,Wisconsin,7065045,121342.0,3458026,59.4,3178783,54.6,266622,2602968,3685570,848,1210467,1709349,258601,366,2921102,50.2
48,West Virginia,2856645,159398.0,847818,47.3,713304,39.8,40323,691096,788944,363,313470,357663,41926,245,671448,37.5
49,Wyoming,602635,104125.0,266342,46.0,227661,39.3,22220,225374,243229,257,98857,108117,20624,63,207102,35.8

In [18]:
#Bradley's Part - Deaths and Tests by State

In [19]:
#import pandas as pd
#import csv

In [20]:
#import data from CSV file
covid_deaths_df = pd.read_csv('united_states_covid19_cases_deaths_and_testing_by_state.csv')

covid_deaths_df

,State/Territory,Level of Community Transmission,Total Cases,Confirmed Cases,Probable Cases,Cases in Last 7 Days,Case Rate per 100000,Total Deaths,Confirmed Deaths,Probable Deaths,...,% Positive Last 30 Days,% Positive Last 7 Days,# Tests per 100K,Total # Tests,# Tests per 100K Last 7 Days,Total # Tests Last 7 Days,# Tests per 100K Last 30 Days,Total # Tests Last 30 Days,New Cases,New Deaths
0,Alabama,high,727360.0,553190.0,174170.0,27631.0,14834.0,12420.0,9802.0,2618.0,...,20-24.9%,20-24.9%,111283.05,5456414.0,2073.77,101681.0,8673.57,425281.0,2672.0,4.0
1,Alaska,high,86598.0,0.0,0.0,2607.0,11838.0,435.0,NaN,NaN,...,5-7.9%,8-9.9%,363903.52,2662118.0,1744.53,12762.0,7832.05,57295.0,0.0,0.0
2,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arizona,high,1032808.0,949435.0,83373.0,21707.0,14189.0,18999.0,16934.0,2065.0,...,10-14.9%,10-14.9%,132553.53,9648196.0,2566.89,186837.0,11788.92,858082.0,2378.0,1.0
4,Arkansas,high,464732.0,0.0,0.0,14467.0,15400.0,7070.0,NaN,NaN,...,10-14.9%,10-14.9%,110649.86,3339196.0,1842.20,55594.0,8955.35,270255.0,937.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Virginia,high,788917.0,597464.0,191453.0,22482.0,9243.0,11947.0,10098.0,1849.0,...,10-14.9%,10-14.9%,110396.43,9422908.0,1932.85,164979.0,7490.21,639328.0,2392.0,13.0
58,Washington,high,575490.0,0.0,0.0,15728.0,7557.0,6691.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
59,West Virginia,high,199300.0,153845.0,45455.0,10640.0,11121.0,3148.0,NaN,NaN,...,10-14.9%,10-14.9%,178924.78,3206595.0,4284.41,76783.0,13411.62,240356.0,1316.0,24.0
60,Wisconsin,high,745707.0,671463.0,74244.0,14298.0,12808.0,8536.0,7666.0,870.0,...,8-9.9%,8-9.9%,184769.51,10758083.0,2597.38,151231.0,10106.22,588428.0,1492.0,7.0
61,Wyoming,high,77206.0,63539.0,13667.0,2450.0,13340.0,858.0,858.0,0.0,...,10-14.9%,10-14.9%,161924.74,937154.0,3738.00,21634.0,12641.70,73165.0,0.0,0.0

In [21]:
# Rename "New York*" to "New York"
covid_deaths_df['State/Territory'] = covid_deaths_df['State/Territory'].replace(['New York*'],'New York')

In [22]:
# Create US States list
states_list = 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'

In [23]:
# Remove values in "State/Territory" column that are not the 50 US States
covid_deaths_states = covid_deaths_df[covid_deaths_df['State/Territory'].isin(states_list)]

# Rename "State/Territory" column to "State"
covid_deaths_states.rename(columns={'State/Territory':'State'}, inplace=True)

# Reset the index
covid_deaths_states.reset_index(drop=True, inplace=True)

/Users/gardnerguzman/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [24]:
# Create a new dataframe with only the columns we need to answer our questions
covid_deaths_st_need = covid_deaths_states[['State','Total Cases','Total Deaths']]
covid_deaths_st_need.head(10)

         State  Total Cases  Total Deaths
0      Alabama     727360.0       12420.0
1       Alaska      86598.0         435.0
2      Arizona    1032808.0       18999.0
3     Arkansas     464732.0        7070.0
4   California    4489496.0       65990.0
5     Colorado     627415.0        7225.0
6  Connecticut     375135.0        8394.0
7     Delaware     122370.0        1891.0
8      Florida    3364998.0       46973.0
9      Georgia    1433714.0       23120.0

In [25]:
#Work on merging the tables together and grouping the data by state

In [26]:
covid_deaths_st_need.dtypes

State            object
Total Cases     float64
Total Deaths    float64
dtype: object

In [27]:
hourly_wage_by_state.dtypes

Hourly Wage    object
State          object
dtype: object

In [51]:
hourly_wage_by_state["Hourly Wage"]=hourly_wage_by_state["Hourly Wage"].str.replace("-","0").astype('float32')

<ipython-input-51-7f87bb31722a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_wage_by_state["Hourly Wage"]=hourly_wage_by_state["Hourly Wage"].str.replace("-","0").astype('float32')

In [52]:
hourly_wage_by_state.dtypes

Hourly Wage    float32
State           object
dtype: object

In [53]:
#vaccination_table = pd.merge(covid_deaths_st_need,hourly_wage_by_state, how="inner", on=["State"])
vaccination_table = pd.merge(covid_deaths_st_need, hourly_wage_by_state, on=['State'])
vaccination_table

          State  Total Cases  Total Deaths  Hourly Wage
0       Alabama     727360.0       12420.0    23.389999
1       Alabama     727360.0       12420.0    28.360001
2       Alabama     727360.0       12420.0    31.410000
3       Alabama     727360.0       12420.0    37.459999
4       Alabama     727360.0       12420.0    49.110001
...         ...          ...           ...          ...
433764  Wyoming      77206.0         858.0    16.180000
433765  Wyoming      77206.0         858.0    18.559999
433766  Wyoming      77206.0         858.0    12.290000
433767  Wyoming      77206.0         858.0    13.840000
433768  Wyoming      77206.0         858.0    15.050000

[433769 rows x 4 columns]

In [58]:
data_df.dtypes

State                                                                 object
Total Doses Delivered                                                  int64
Doses Delivered per 100K                                             float64
People with at least One Dose by State of Residence                    int64
Percent of Total Pop with at least One Dose by State of Residence    float64
People Fully Vaccinated by State of Residence                          int64
Percent of Total Pop Fully Vaccinated by State of Residence          float64
Total Number of Janssen doses administered                             int64
Total Number of Moderna doses administered                             int64
Total Number of Pfizer doses adminstered                               int64
Total Number of doses from unknown manufacturer administered           int64
People Fully Vaccinated Moderna Resident                               int64
People Fully Vaccinated Pfizer Resident                                int64
People Fully Vaccinated Janssen Resident                               int64
People Fully Vaccinated Unknown 2-dose manufacturer Resident           int64
People with 2 Doses by State of Residence                              int64
Percent of Total Pop with 2 Doses by State of Residence              float64
dtype: object

In [59]:
vaccination_table.dtypes

State            object
Total Cases     float64
Total Deaths    float64
Hourly Wage     float32
dtype: object

In [ ]:
#Connect the code to Postgres SQL

In [54]:
rds_connection_string = "postgres:postgres@localhost:5432/COVID"
engine = create_engine(f'postgresql://{rds_connection_string}')
conn = engine.connect()

In [57]:
vaccination_table.to_sql(name='COVID_By_State', con=engine, if_exists='append', index=False)

In [60]:
data_df.to_sql(name='COVID_Vaccinations', con=engine, if_exists='append', index=False)